# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheGoodFork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheGoodFork

  target 'TheGoodForkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheGoodForkUITests' do
    # Pods for testing
  end

end
